# Generated by Django 5.2.8 on 2025-11-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
